---
title: "Boruta-Dim-Redux"
author: "MCC"
date: "8/30/2019"
output: html_document
---

Title:

Libraries  
```{r message=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, cache.lazy = FALSE)

Libraries = c("doMC", "knitr", "Boruta", "readr")

for(p in Libraries){  # Install if not present
    if(!require(p, character.only = TRUE)) { install.packages(p, dependencies = T) }
    library(p, character.only = TRUE)
}
```

Import data
```{r message=FALSE, warning=FALSE}
cancer_human_comps <- read_csv("../1data/cancer_human_comps.csv",
                               col_types = cols(Class = col_factor(levels = c("0","1")), 
                                                PID = col_character()))
#View(cancer_human_comps)

colnames(cancer_human_comps)[244] <- "NA" 
```
First Boruta run; ntree = 50, mtry = 2
```{r, cache=TRUE}
cancer_human_Active <- cancer_human_comps[, c(1, 4:423)]

registerDoMC(cores = 3) # Start multi-processor mode
start_time <- Sys.time() # Start timer

set.seed(1000)
Boruta_cancer_human_Active <- Boruta(Class ~ ., data = cancer_human_Active, doTrace = 1, mtry = 2, ntree = 500)

registerDoSEQ() # Stop multi-processor mode
Sys.time() - start_time  # Display time difference
```
Show Model Info
```{r}
Boruta_cancer_human_Active
```

```{r fig.width=7.25}
plot(Boruta_cancer_human_Active)
```

Get Formula
```{r}
getConfirmedFormula(Boruta_cancer_human_Active)
```

Results from **Boruta_cancer_human_Active**

- Class ~ 







