---
title: "Corrplot using post Boruta dataset"
author: "MCC"
date: "8/31/2019"
output: html_document
---

Libraries  
```{r message=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(cache = TRUE, warning = FALSE, message = FALSE, cache.lazy = FALSE)

Libraries = c("doMC", "readr", "ggplot2", "caret")

# Load Libraries
for(p in Libraries){ library(p, character.only = TRUE) }
```

Import data
```{r message=FALSE, warning=FALSE}
cancer_human_comps <- read_csv("../1data/cancer_human_comps.csv",
                               col_types = cols(Class = col_factor(levels = c("0","1"))))
#View(cancer_human_comps)
#head(cancer_human_comps)

colnames(cancer_human_comps)[244] <- "NA" 

cancer_human_Active <- cancer_human_comps[, c("A", "C", "D", "E", "F", "G", "H", "K", "L", "N", "Q", "R", "S", "T", "V", "Y", "AA", "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AP", "AR", "AT", "AV", "AY", "CA", "CC", "CE", "CF", "CG", "CI", "CK", "CL", "CN", "CP", "CQ", "CR", "CS", "CV", "CY", "DA", "DC", "DD", "DG", "DK", "DP", "DQ", "DR", "DS", "DW", "EA", "EC", "EE", "EK", "EN", "ES", "FA", "FC", "FK", "FL", "FT", "GA", "GC", "GD", "GG", "GL", "GR", "GT", "GV", "HC", "HK", "HS", "IA", "ID", "IG", "KC", "KD", "KE", "KF", "KH", "KK", "KN", "KQ", "KR", "KS", "KY", "LA", "LC", "LE", "LH", "LL", "LQ", "LS", "ME", "NA", "NC", "NI", "NK", "NS", "PA", "PC", "PD", "PS", "PT", "PV", "QC", "QE", "QK", "QL", "RA", "RD", "RE", "RI", "RK", "RM", "SA", "SC", "SE", "SK", "SL", "SP", "SQ", "SS", "ST", "TA", "TC", "TD", "TG", "TK", "TS", "TT", "TV", "VA", "VC", "YA", "YC", "YF", "YL")]
```


Zero- and Near Zero-Variance Predictors for 142 features. 
```{r fig.height=7, fig.width=7}
registerDoMC(cores = 3) # Start multi-processor mode

nzero_var <- nearZeroVar(cancer_human_Active, saveMetrics = TRUE)

registerDoSEQ() # Stop multi-processor mode

names(nzero_var)
```

```{r}
nzero_var[nzero_var$nzero_var,][1:10,]
```

Results: **No Predictors have near-zero-variance.**

